### ISSUE TITLE
main.exe打开后没有反应

### ISSUE THREAD

**Issue by AlanGong1** [appcell/OverwatchDataAnalysis#26]
打开后出现一个黑框，里面是一部分数据，一秒后消失，什么都没有发生。
使用系统是win10

**Comment by AlanGong1** [comment]
已经解决了，我把文件从固态E盘移到C盘里就可以用了

**Comment by appcell** [comment]
谢啦 这个我们在查了

**Comment by AlanGong1** [comment]
又无法运行了，不论移到哪个文件都打不开

**Comment by Rigel7** [comment]
用cmd打开main.exe，看看有没有错误输出？

**Comment by AlanGong1** [comment]
用cmd打开依然还是没有反应，出现一堆英文看不懂

**Comment by Rigel7** [comment]
能否把出现的东西截图发上来？谢谢！另外你的CPU是Intel的还是AMD的？

**Comment by AlanGong1** [comment]
CPU是intel的，已经解决了，应该是路径不可以有英文

**Comment by Rigel7** [comment]
你说的是不能有中文吧？这个确实是。

**Comment by soksrlc** [comment]
win8系统 也是打开一个黑框然后秒关……文件是在C盘里……

**Comment by Rigel7** [comment]
@soksrlc 参考一下之前的回复，是不是文件路径里面有中文？

**Comment by soksrlc** [comment]
应该没有中文呀，然后用cmd打开也是一样的qaq

**Comment by Rigel7** [comment]
用cmd打开应该会有错误提示，不会直接消失。能不能把错误提示发一下？

**Comment by soksrlc** [comment]
有一长串，最后是 [9784]Failed to execute script main  不知道怎么发图……

**Comment by Rigel7** [comment]
全复制过来就好...

**Comment by soksrlc** [comment]
C:\Users\LHN>C:\ORA_v0.1_beta_Windows_64bit\main.exe
Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "c:\users\luojiawei\appdata\local\temp\pip-build-aw6571\pyinstaller\PyIns
taller\loader\pyimod03_importers.py", line 396, in load_module
  File "ora\game.py", line 1, in <module>
  File "c:\users\luojiawei\appdata\local\temp\pip-build-aw6571\pyinstaller\PyIns
taller\loader\pyimod03_importers.py", line 396, in load_module
  File "ora\overwatch.py", line 1, in <module>
  File "c:\users\luojiawei\appdata\local\temp\pip-build-aw6571\pyinstaller\PyIns
taller\loader\pyimod03_importers.py", line 396, in load_module
  File "ora\utils\image.py", line 3, in <module>
  File "c:\users\luojiawei\appdata\local\temp\pip-build-aw6571\pyinstaller\PyIns
taller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\skimage\transform\__init__.py", line 1, in <module>
  File "c:\users\luojiawei\appdata\local\temp\pip-build-aw6571\pyinstaller\PyIns
taller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\skimage\transform\hough_transform.py", line 4, in <module>

  File "c:\users\luojiawei\appdata\local\temp\pip-build-aw6571\pyinstaller\PyIns
taller\loader\pyimod03_importers.py", line 687, in load_module
  File "skimage\transform\_hough_transform.pyx", line 13, in init skimage.transf
orm._hough_transform
  File "c:\users\luojiawei\appdata\local\temp\pip-build-aw6571\pyinstaller\PyIns
taller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\skimage\draw\__init__.py", line 1, in <module>
  File "c:\users\luojiawei\appdata\local\temp\pip-build-aw6571\pyinstaller\PyIns
taller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\skimage\draw\draw.py", line 4, in <module>
  File "c:\users\luojiawei\appdata\local\temp\pip-build-aw6571\pyinstaller\PyIns
taller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\skimage\_shared\_geometry.py", line 4, in <module>
  File "c:\users\luojiawei\appdata\local\temp\pip-build-aw6571\pyinstaller\PyIns
taller\loader\pyimod03_importers.py", line 396, in load_module
  File "site-packages\matplotlib\__init__.py", line 1060, in <module>
  File "site-packages\matplotlib\__init__.py", line 892, in rc_params
  File "site-packages\matplotlib\__init__.py", line 736, in matplotlib_fname
  File "site-packages\matplotlib\__init__.py", line 733, in gen_candidates
  File "ntpath.py", line 85, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 7: ordinal
not in range(128)
[9784] Failed to execute script main

**Comment by appcell** [comment]
@soksrlc 你好，能留个联系方式吗？这个问题我们无法复现，想麻烦你和我们一起尝试一下。如果方便可以加qq群：552707537

**Comment by soksrlc** [comment]
好的，我已经申请加群了~

**Comment by Rigel7** [comment]
A strange coding problem in python2. We have switched to python3 and shouldn't see this kind of error again.
