### ISSUE TITLE
Game.set_team_colors not called

### ISSUE THREAD

**Issue by Rigel7** [appcell/OverwatchDataAnalysis#5]
When analyzing seoul_vs_huston_m2r1.mp4, the program returns an error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\lib-tk\Tkinter.py", line 1542, in __call__
    return self.func(*args)
  File "D:\OverwatchDataAnalysis\python\gui.py", line 180, in run
    analyze(gui_info)
  File "D:\OverwatchDataAnalysis\python\gui.py", line 33, in analyze
    game.analyze(0, 0)
  File "D:\OverwatchDataAnalysis\python\game.py", line 153, in analyze
    self.output_to_excel()
  File "D:\OverwatchDataAnalysis\python\game.py", line 173, in output_to_excel
    Excel(self).save()
  File "D:\OverwatchDataAnalysis\python\excel\__init__.py", line 20, in __init__
    self.sheet1 = Sheet1(self._wb, game)
  File "D:\OverwatchDataAnalysis\python\excel\sheet1.py", line 221, in __init__
    Config.team_colors[self.game.team_names['left']] = utils.to_hex(self.game.team_colors['left'])
TypeError: 'NoneType' object has no attribute '__getitem__'

It seems that Game.set_team_colors method was not called, thus the team colors are not set.

**Comment by Rigel7** [comment]
This is because `opencv2` can't find the codec to read the video file. Switching to `scikit-video` might solve the problem.

**Comment by Rigel7** [comment]
On Windows, installing `opencv2` with `pip install opencv-python` will solve this problem.
